helmDefaults:
  wait: true
  atomic: true
  timeout: 120

repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 2.13.0
  values:
  - values/ingress-nginx.yaml